modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "vsrnd"
version = "${version}"
displayName = "Create x Valkyrien Skies Template"
authors = ["potato", "fern", "dacodia", "toni"]
description = '''
A template mod for Create x Valkyrien Skies mods.
'''
logoFile = "KlarksonLogoResized.png"

[[dependencies.vsrnd]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vsrnd]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.vsrnd]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vsrnd]]
modId = "create"
mandatory = true
versionRange = "${create_forge_version}"
ordering = "NONE"
side = "BOTH"
