modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "rnd"
version = "${version}"
displayName = "Create: Research & Development"
authors = ["fluffy", "potato", "ewoudje"]
description = '''
A gameplay overhaul for MC!
'''
logoFile = "icon.png"

[[dependencies.rnd]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rnd]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.rnd]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.rnd]]
modId = "create"
mandatory = true
versionRange = "${create_version}"
ordering = "NONE"
side = "BOTH"
